package Task::BeLike::SHARYANTO::Authored;
# ABSTRACT: Install all modules authored by SHARYANTO on CPAN

# note: list of pkgs generated by generate-pkg-lists-for-tbsha

our $VERSION = '0.08'; # VERSION


1;

__END__
=pod

=head1 NAME

Task::BeLike::SHARYANTO::Authored - Install all modules authored by SHARYANTO on CPAN

=head1 VERSION

version 0.08

=head1 DESCRIPTION

This task will install all modules authored by SHARYANTO currently on CPAN.
Excluded are other Task::* modules, or modules already deletd from CPAN.

=head1 TASK CONTENTS

=head2 Included modules

=head3 L<Acme::CPANAuthors::Indonesian>

=head3 L<Any::Renderer::Pretty::Console>

=head3 L<Any::Renderer::Pretty::HTML>

=head3 L<App::HTMLCalendarMonth::Indonesia>

=head3 L<App::OrgUtils>

=head3 L<App::SerializeUtils>

=head3 L<App::UniqFiles>

=head3 L<App::perlmv>

=head3 L<Array::Find>

=head3 L<Array::Functions::Undoable>

=head3 L<Array::Iterator>

=head3 L<Bench>

=head3 L<Builtin::Logged>

=head3 L<Business::BankCard>

=head3 L<Business::BankCard::Indonesia>

=head3 L<Business::BankList>

=head3 L<Business::BankList::Indonesia>

=head3 L<Business::ID::NIK>

=head3 L<Business::ID::NOPPBB>

=head3 L<Business::ID::NPWP>

=head3 L<Business::ID::SIM>

=head3 L<CPAN::Critic::Module::Abstract>

=head3 L<Calendar::Indonesia::Holiday>

=head3 L<Config::Ini::OnDrugs>

=head3 L<Data::Dump::Ala::SHARYANTO>

=head3 L<Data::Dump::Color>

=head3 L<Data::Dump::OneLine>

=head3 L<Data::Dump::PHP>

=head3 L<Data::Dump::Partial>

=head3 L<Data::Dump::Ruby>

=head3 L<Data::Format::Pretty>

=head3 L<Data::Format::Pretty::Console>

=head3 L<Data::Format::Pretty::HTML>

=head3 L<Data::Format::Pretty::JSON>

=head3 L<Data::Format::Pretty::PHP>

=head3 L<Data::Format::Pretty::PHPSerialization>

=head3 L<Data::Format::Pretty::Perl>

=head3 L<Data::Format::Pretty::Ruby>

=head3 L<Data::Format::Pretty::YAML>

=head3 L<Data::ModeMerge>

=head3 L<Data::Sah>

=head3 L<Data::Sah::Util>

=head3 L<Data::Unixish>

=head3 L<Data::Unixish::Implementation>

=head3 L<Devel::EndStats>

=head3 L<Dist::Zilla::PluginBundle::SHARYANTO>

=head3 L<File::RsyBak>

=head3 L<File::Slurp::Shortcuts>

=head3 L<File::Trash::FreeDesktop>

=head3 L<File::Trash::Undoable>

=head3 L<Finance::Bank::ID::BCA>

=head3 L<Finance::Bank::ID::BPRKS>

=head3 L<Finance::Bank::ID::Mandiri>

=head3 L<Finance::Currency::Convert::KlikBCA>

=head3 L<Gepok>

=head3 L<Git::Bunch>

=head3 L<HTTP::Daemon::UNIX>

=head3 L<HTTP::Daemon::patch::ipv6>

=head3 L<LWP::Protocol::http::SocketUnixAlt>

=head3 L<LWP::UserAgent::patch::https_hard_timeout>

=head3 L<LWP::UserAgent::patch::log_response>

=head3 L<Language::Expr>

=head3 L<Ledger::Parser>

=head3 L<Lingua::EN::Number::Format::MixWithWords>

=head3 L<Lingua::ID::Number::Format::MixWithWords>

=head3 L<Lingua::ID::Nums2Words>

=head3 L<Lingua::ID::Words2Nums>

=head3 L<Lingua::ZH::PinyinConvert::ID>

=head3 L<Locale::ID::GuessGender::FromFirstName>

=head3 L<Locale::ID::Locality>

=head3 L<Locale::ID::Province>

=head3 L<Log::Any::Adapter::Callback>

=head3 L<Log::Any::Adapter::ScreenColoredLevel>

=head3 L<Log::Any::App>

=head3 L<Log::Any::For::Class>

=head3 L<Log::Any::For::DBI>

=head3 L<Log::Any::For::LWP>

=head3 L<Log::Dispatch::Dir>

=head3 L<Module::Patch>

=head3 L<Net::HTTP::Methods::patch::log_request>

=head3 L<Object::BlankStr>

=head3 L<Object::NulStr>

=head3 L<Object::SpaceBackStr>

=head3 L<Org::Parser>

=head3 L<Org::To::HTML>

=head3 L<Org::To::Pod>

=head3 L<Org::To::Text>

=head3 L<Parse::Netstat>

=head3 L<Parse::Number::EN>

=head3 L<Parse::Number::ID>

=head3 L<Parse::PhoneNumber::ID>

=head3 L<Parse::VarName>

=head3 L<Passwd::Unix::Alt>

=head3 L<Perinci>

=head3 L<Perinci::Access::HTTP::Client>

=head3 L<Perinci::Access::HTTP::Server>

=head3 L<Perinci::Access::TCP::Client>

=head3 L<Perinci::Access::TCP::Server>

=head3 L<Perinci::BashComplete>

=head3 L<Perinci::CmdLine>

=head3 L<Perinci::Examples>

=head3 L<Perinci::Gen::ForModule>

=head3 L<Perinci::Object>

=head3 L<Perinci::Sub::ConvertArgs::Array>

=head3 L<Perinci::Sub::DepChecker>

=head3 L<Perinci::Sub::Gen::AccessTable>

=head3 L<Perinci::Sub::Gen::AccessTable::DBI>

=head3 L<Perinci::Sub::Gen::Undoable>

=head3 L<Perinci::Sub::GetArgs::Argv>

=head3 L<Perinci::Sub::GetArgs::Array>

=head3 L<Perinci::Sub::Wrapper>

=head3 L<Perinci::Sub::property::drops_privilege>

=head3 L<Perinci::Sub::property::result_postfilter>

=head3 L<Perinci::Sub::property::retry>

=head3 L<Perinci::Sub::property::timeout>

=head3 L<Perinci::To::HTML>

=head3 L<Perinci::To::POD>

=head3 L<Perinci::To::Text>

=head3 L<Perinci::Tx::Manager>

=head3 L<Perinci::Use>

=head3 L<Pod::Weaver::Plugin::Perinci>

=head3 L<Process::KillTree>

=head3 L<RSS::From::Forum::vBulletin>

=head3 L<Riap>

=head3 L<Rinci>

=head3 L<SHARYANTO::String::Util>

=head3 L<SHARYANTO::Utils>

=head3 L<Serabi>

=head3 L<Setup>

=head3 L<Setup::File>

=head3 L<Setup::File::Symlink>

=head3 L<Setup::Multi>

=head3 L<Setup::Test>

=head3 L<Setup::Text::Snippet>

=head3 L<Setup::Unix::User>

=head3 L<Test::Setup>

=head3 L<Text::PrettyTable>

=head3 L<Text::sprintfn>

=head3 L<Tie::Diamond>

=head3 L<WWW::GudangAPI>

=head1 AUTHOR

Steven Haryanto <stevenharyanto@gmail.com>

=head1 COPYRIGHT AND LICENSE

This software is copyright (c) 2012 by Steven Haryanto.

This is free software; you can redistribute it and/or modify it under
the same terms as the Perl 5 programming language system itself.

=cut

